config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#about'
  resources :responses
  resources :quizzes do
    collection do
      get 'create_test'
      post 'create_test'
    end
    member do
        get 'results'
    end
  end
  resources :sounds do
    collection do
      get 'search'
    end
  end
  resources :groups
  resources :users do
    member do
      get 'quiz_history'
      get 'test_history'
      get 'user_statistics', to: 'statistics#user_statistics', as: 'user_statistics'
      get 'open_join_group'
      post 'join_group'
    end
  end
  match '/login', to: 'sessions#new', via: :get, :as => 'login'
  match '/login/create', to: 'sessions#create', via: :post, :as => 'sessions'
  match '/about', to: 'pages#about', via: :get, :as => 'about'
  match '/logout', to: 'sessions#destroy', via: :delete, :as => 'logout'
  match '/learn', to: 'pages#learn', via: :get, :as => 'learn'
  match '/tab_groups', to: 'pages#tab_group', via: :get, :as => 'tabGroup'
  match '/tutorial', to: 'pages#tutorial', via: :get, :as => 'tutorial'
  get 'data/audio/:filename', to: 'sounds#audio', as: 'audio', constraints: { filename: /[^\/]+/ }
  get '/quizzes/data/audio/:filename', to: 'sounds#audio', constraints: { filename: /[^\/]+/ }
  get '/sounds/data/audio/:filename', to: 'sounds#audio', constraints: { filename: /[^\/]+/ }
  get 'sounds/:sound_id/responses', to: 'responses#show_responses', as: 'responses_sound'
  get 'statistics/group/:join_token', to: 'statistics#group_statistics', as: 'group_statistics'
  get 'statistics/site', to: 'statistics#site_statistics', as: 'site_statistics'
  get 'search_users', to: 'users#search_users'
  post 'change_access', to: 'users#change_access'
end

app/controllers/quizzes_controller.rb
/
This page is very important handling tests and quizzes.
/
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  def index
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    if @quiz.which_grbas_letter.empty?
      render :show_test
    else
      render :show
    end
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  # Serves a quiz if you can create a test with the given parameters.
  def create
    @quiz, error = Quiz.build_quiz params[:quiz][:which_grbas_letter],
                            params[:quiz][:difficulty].to_i,
                            params[:quiz][:num_questions].to_i,
                            @current_user.id
    if not @quiz.nil? and @quiz.save
      flash[:notice] = "Quiz created successfully!"
      unless @current_user.nil?
        @current_user.quizzes << @quiz
      end
      redirect_to quiz_path(@quiz)
    else
      flash[:alert] = error
      @quiz = Quiz.new
      render :new
    end
  end

  # Serves a test if you can create a test with the given parameters.
  def create_test
    if request.post?
      stat = Stat.find_by_user_id(@current_user.id)
      if stat.progress_level.eql?("beginner")
        difficulty = 3
      else
        difficulty = 1
      end

      @quiz, error = Quiz.build_test difficulty,
                                     params[:quiz][:num_questions].to_i,
                                     @current_user.id
      if not @quiz.nil? and @quiz.save
        flash[:notice] = "Test created successfully!"
        unless @current_user.nil?
          @current_user.quizzes << @quiz
        end
        redirect_to quiz_path(@quiz)
      else
        flash[:alert] = error
        @quiz = Quiz.new
        render :create_test
      end
    else
      @quiz = Quiz.new
      render :create_test
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  # app/controllers/quizzes_controller.rb
  # Grades/saves quiz or test. The grbas loop hits once for quizzes and every time for tests.
def update
  @quiz = Quiz.find(params[:id])
  num_right = 0
  total_qs = 0
  complete = ActiveModel::Type::Boolean.new.cast(quiz_params[:complete])
  quiz_params[:responses].each do |response|
    @response = Response.find_by_id(response[0])
    feedback = ""
    # Tests should have response for each question
    ['g', 'r', 'b', 'a', 's'].each do |letter|
      letter_sym = "#{letter}_rating".to_sym
      # Quiz will only pass this once
      unless response[1][letter_sym].nil? || response[1][letter_sym].empty?
        @response.update({ letter_sym => response[1][letter_sym], # letter_sym is g_rating, r_rating, etc.
                           :reasoning => response [1][:reasoning], :quiz_id => @quiz.id })
        # Test feedback is each letter and its feedback on their own lines
        feedback_string, correct = @response.create_feedback(letter)
        feedback = feedback + "\n#{letter.upcase}: " + feedback_string
        num_right += 1 if correct
        total_qs += 1
      end
      @response.update({ :feedback => feedback })
    end
  end
  # This should pass true for completed if the user submits but not if they click save
  @quiz.update({ :completed => complete, :num_right => num_right })
  if @quiz.save
    if complete
      @stat = Stat.find_by_user_id(@current_user.id)
      @stat.update_experience([num_right, total_qs])
      flash[:notice] = "Quiz/Test completed successfully! Find your results in Quiz or Test History!"
      redirect_to results_quiz_path(@quiz.id)
    else
      flash[:notice] = "Quiz/Test saved successfully! Return to it later through Quiz or Test History!"
      redirect_to user_path(@current_user.id)
    end
    # Redirect to page where their results are one click away
  else
    render :edit
  end
end

  def results
    @quiz = Quiz.find(params[:id])
    @hostname = (request.url).to_s.split("/")[2]
  end


  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
      @responses = @quiz.responses
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:which_grbas_letter, :difficulty, :num_questions, :complete,
                                   responses: [:g_rating, :r_rating, :b_rating, :a_rating, :s_rating, :reasoning])
    end

    def test_params
      params.require(:quiz).permit(:difficulty, :num_questions, responses: [:rating, :reasoning])
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/create_test.html.erb
<!-- app/views/quizzes/create_test.html.erb -->
<h1 class="mb-4">New Test</h1>

<div>
  <p><strong>Select the number of questions you’d like to practice with. Then Create Test!
  </strong></p>
</div>

<%= form_for @quiz, url: create_test_quizzes_path do |f| %>
  <div class="form-group">
    <%= f.label :num_questions, 'Number of Questions (Limit 50)', class: 'form-label' %>
    <%= f.number_field :num_questions, in: 1..50, class: 'form-control custom-input' %>
    <% if @quiz.errors[:num_questions].any? %>
      <div class="error"><%= @quiz.errors[:num_questions].join(", ") %></div>
    <% end %>
  </div>

  <div class="text-center">
    <%= f.submit "Create Test", class: 'btn btn-grey' %>
  </div>
<% end %>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const difficultyButtons = document.querySelectorAll('.difficulty-btn');
        difficultyButtons.forEach(function(button) {
            button.addEventListener('click', function(e) {
                e.preventDefault();
                const difficulty = this.getAttribute('data-difficulty');
                const difficultyField = this.parentElement.querySelector('.difficulty-field');
                difficultyField.value = difficulty;

                // Remove active class from all buttons in this group
                this.parentElement.querySelectorAll('.difficulty-btn').forEach(function(btn) {
                    btn.classList.remove('active');
                });

                // Add active class to clicked button
                this.classList.add('active');
            });
        });
    });
</script>

<style>
    .difficulty-buttons {
        display: flex;
        align-items: center;
        margin-bottom: 15px;
    }
    .difficulty-btn {
        background-color: lightgrey;
        margin-right: 5px;
        color: black; /* Ensure text color is black when not active */
    }
    .difficulty-btn.active {
        background-color: #007bff; /* Change this to your preferred active color */
        color: white;
    }
    .error {
        color: #dc3545; /* Bootstrap danger color */
        font-size: 0.875em;
        margin-top: 5px;
    }
</style>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quizzes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/results.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
<%= csrf_meta_tags %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<%= link_to "Take Another Quiz", new_quiz_path, class: 'btn custom-lightgrey-btn' %>
<%= link_to "Quiz History", quiz_history_user_path(@current_user.id), class: 'btn custom-lightgrey-btn' %>

<div class="header-container">
  <h1>Quiz Results</h1>
</div>
  <% if @quiz.which_grbas_letter.nil? || @quiz.which_grbas_letter.empty? %>
    <h3>Score: <%= (@quiz.num_right.to_f / (@quiz.num_questions * 5) * 100).round(2) %>% (<%= @quiz.num_right %> out of <%= (@quiz.num_questions * 5) %>)</h3>
    <h2><%= @quiz.which_grbas_letter.upcase %></h2>
    <p>Difficulty: <%= @quiz.difficulty %></p>
    <p>Number of Questions: <%= @quiz.num_questions %></p>
    <p>Taken On: <%= @quiz.created_at.in_time_zone("Central Time (US & Canada)").strftime("%B %d, %Y at %I:%M%p") %></p>
  <div class="btn-container">
    <%= link_to "Take Another Quiz", new_quiz_path, class: 'btn custom-lightgrey-btn' %>
    <%= link_to "Quiz History", quiz_history_user_path(@current_user.id), class: 'btn custom-lightgrey-btn' %>
  </div>
  <% @quiz.responses.each_with_index do |response, index| %>
    <div class="response-box">
      <h3>Question <%= index + 1 %>:</h3>
      <audio controls class="mb-3">
        <% filepath = Sound.find_by_id(response.sound_id).audio_file_path %>
        <source src=<%="http://#{@hostname}/#{filepath}"%> type="audio/wav">
        Your browser does not support the audio element.
      </audio>

      <% split_response = response.feedback.split("\n") %>
      <div>
        <table>
          <thead>
          <tr>
            <th>Your Rating</th>
            <th>Expert Feedback</th>
          </tr>
          </thead>
          <tbody>
          <% ["g", "r", "b", "a", "s"].each_with_index do |letter, index| %>
            <tr>
              <td><%= letter.upcase %><%= response["#{letter}_rating".to_sym] %></td>
              <td><%= split_response[index + 1] %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <p><strong>Your Notes:</strong> <%= response.reasoning %></p>
      <p><strong>Sound:</strong> <%= Sound.find_by_id(response.sound_id).db_file_name %></p>
    </div>
  <% end %>
<% else %>
  <h3>Score: <%= (@quiz.num_right.to_f / @quiz.num_questions * 100).round(2) %>% (<%= @quiz.num_right %> out of <%= @quiz.num_questions %>)</h3>

  <% @quiz.responses.each_with_index do |response, index| %>
    <div class="response-box">
      <h3>Question <%= index + 1 %>:</h3>
      <audio controls class="mb-3">
        <% filepath = Sound.find_by_id(response.sound_id).audio_file_path %>
        <source src=<%="http://#{@hostname}/#{filepath}"%> type="audio/wav">
        Your browser does not support the audio element.
      </audio>

      <p><strong>Rating:</strong> <%= response["#{@quiz.which_grbas_letter}_rating".to_sym] %></p>
      <p><strong>Expert Feedback:</strong> <%= response.feedback %></p>
      <p><strong>Your Notes:</strong> <%= response.reasoning %></p>
      <p><strong>Sound:</strong> <%= Sound.find_by_id(response.sound_id).db_file_name %></p>
    </div>
  <% end %>
<% end %>

<style>
    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }
     .custom-lightgrey-btn {
         background-color: lightgrey;
         color: black;
         border: none;
     }
    .custom-lightgrey-btn:hover {
        background-color: grey;
        color: white;
    }
</style>

app/views/quizzes/show.html.erb
<!DOCTYPE html>
<html lang="">
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag 'quiz', media: 'all', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'quiz_buttons' %>
</head>
<h1 class="mb-4">Quiz for : "<%= Quiz.translate_letter(@quiz.which_grbas_letter) %>" </h1>

<div>
  <p>
  Now, for each sound sample, consider select the number on the letter’s scale that you feel best represents the level of disorder. You can also
  you can also add a note/description in the question box about why you feel this is the best answer. (These notes are only for your reference when reviewing your quiz history later).
  You can listen to a sound any number of times and there are no time limits for quizzes. Feel free to
  adjust the volume as needed. You may need to use the the manual controls on your device.
  </p>
  <p>
  Once you’ve answered all the questions, you can submit the quiz by selecting “Submit Quiz”.
  This will complete the quiz and take you to your user profile to see your results.
  If for some reason you need to quit the quiz and come back to it, hit the “Save Quiz” button.
  </p>
</div>


<%= form_for @quiz, url: {action: "update"}, html: { class: 'needs-validation', novalidate: true } do |f| %>
  <!-- Jank works to autofill values -->
  <% @responses.each_with_index do |response, index| %>
    <%= f.fields_for :responses do |response_fields| %>
      <!-- Set the value of each response field to the corresponding value from the saved response -->
      <%= response_fields.text_field :g_rating, value: response.g_rating, class: "response-#{index}-g-rating", style: "display: none;" %>
      <%= response_fields.text_field :r_rating, value: response.r_rating, class: "response-#{index}-r-rating", style: "display: none;" %>
      <%= response_fields.text_field :b_rating, value: response.b_rating, class: "response-#{index}-b-rating", style: "display: none;" %>
      <%= response_fields.text_field :a_rating, value: response.a_rating, class: "response-#{index}-a-rating", style: "display: none;" %>
      <%= response_fields.text_field :s_rating, value: response.s_rating, class: "response-#{index}-s-rating", style: "display: none;" %>
      <%= response_fields.text_field :reasoning, value: response.reasoning, class: "response-#{index}-reasoning", style: "display: none;" %>
    <% end %>
  <% end %>

  <% @quiz.quiz_answers.each_with_index do |answer, index| %>
    <%= f.fields_for :responses do |response_fields| %>
      <!-- Save the values of true answers for JS to read (jank ik) -->
      <%= response_fields.text_field :answer, value: answer, class: "answer-#{index}", style: "display: none;" %>
    <% end %>
  <% end %>

  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" style="width: 0" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <% @quiz.responses.each_with_index do |response, index| %>
    <div class="question-container<%= index == 0 ? '' : ' d-none' %>">
      <%= f.fields_for :responses, index: response.id do |response_fields| %>
        <div class="card mb-3">
          <div class="card-body">
            <h2 class="card-title">Question <%= index + 1 %></h2>
            <p> Please listen for ~10 seconds before answering the question. Also, the "Ahhh" may play at the end of the sample.</p>
            <audio id="audio_elem_<%= index %>" controls class="mb-3">
              <source src="<%= response.sound.audio_file_path %>" type="audio/wav">
              Your browser does not support the audio element.
            </audio>

            <p>
              Hint: If you're confused about what the letters on the scale, select the anchor sample button next to the letter
              that you're listening for. This will display another audio player with a sound that is considered a level 3
              score for that voice characteristic.
            </p>

            <div class="form-group">
              <label class="form-label">Rate the sound (0-3):</label>
              <div id="rating-buttons-<%= index %>" class="rating-buttons">
                <% (0..3).each do |rating| %>
                  <button type="button" class="btn btn-secondary rating-btn" data-rating="<%= rating %>"><%= rating %></button>
                <% end %>
                <%= response_fields.hidden_field "#{@quiz.which_grbas_letter}_rating".to_sym, class: "rating-field" %>

                <% if "RBAS".include?(@quiz.which_grbas_letter.upcase) %>
                  <button id="button_anchor_<%= index %>" type="button" class="btn custom-lightgrey-btn" style="text-align:center; background-color: lightgrey; border-color: #4e555b; color: #4e555b">Anchor Sample? </button>
                  <audio id="audio_elem_anchor_<%= index %>" controls class="mb-3" style="display: none">
                    <source src="<%= Sound.get_anchor(@quiz.which_grbas_letter) %>" type="audio/wav">
                    Your browser does not support the audio element.
                  </audio>
                <% end %>
              </div>
            </div>

            <div class="form-group">
              <%= response_fields.label :reasoning, "Notes:", class: 'form-label' %>
              <%= response_fields.text_field :reasoning, class: 'form-control reasoning-field' %>
            </div>

            <button type="button" id="check-question-btn-<%=index%>" class="btn mt-3" style="text-align:center; background-color: lightgrey; border-color: #4e555b; color: #4e555b">Check Your Answer?</button>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if @quiz.num_questions > 1 %>
      <button type="button" class="btn prev-question-btn mt-3">Previous Question</button>
      <button type="button" class="btn next-question-btn mt-3">Next Question</button>
  <% end %>
  <div class="button-container">
    <%= f.hidden_field :complete, value: false, class: 'complete-tag' %>
    <%= f.submit "Complete Quiz", class: 'btn submit-quiz-button btn-grey btn-lg btn-block mt-3' %>
    <%= f.submit "Save Quiz", name: "save", class: 'btn btn-primary mt-3' %>
    <%= link_to 'Back', new_quiz_path, class: 'btn btn-danger mt-3' %>
  </div>
<% end %>

<!-- Bootstrap Modal -->
<div class="modal fade" id="answerModal" tabindex="-1" role="dialog" aria-labelledby="answerModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="answerModalLabel">
          <!-- The answer check label will be inserted here with question number -->
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="answerModalBody">
        <!-- The answer check result will be inserted here -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<style>
  .modal-content {
      background-color: #f9f9f9; /* Change the background color */
      border-radius: 10px; /* Round the corners */
      border: none; /* Remove the default border */
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.15); /* Add a subtle shadow */
  }

  .modal-header {
      border-bottom: none; /* Remove the default border */
  }

  .modal-footer {
      border-top: none; /* Remove the default border */
  }

  .modal-title {
      font-weight: bold; /* Make the title bold */
  }
</style>

app/views/quizzes/show_test.html.erb
<!-- app/views/tests/show.html.erb -->
<!DOCTYPE html>
<html lang="">
<head>
  <title>Test</title>
  <%= stylesheet_link_tag 'quiz', media: 'all', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'quiz_buttons' %>

</head>

<h1 class="mb-4">GRBAS Scale Test</h1>

<div>
  <p>
    Now, for each sound sample, consider select the number on the letter’s scale that you feel best represents the level of disorder. You can also
    you can also add a note/description in the question box about why you feel this is the best answer. (These notes are only for your reference when reviewing your quiz history later).
    You can listen to a sound any number of times and there are no time limits for tests. Feel free to
    adjust the volume as needed. You may need to use the the manual controls on your device.
  </p>
  <p>
    Once you’ve answered all the questions, you can submit the test by selecting “Submit Test”.
    This will complete the quiz and take you to your user profile to see your results.
  </p>
</div>
<%= form_for @quiz, url: {action: "update"}, html: { class: 'needs-validation', novalidate: true } do |f| %>
  <!-- Jank works to autofill values -->
  <% @responses.each_with_index do |response, index| %>
    <%= f.fields_for :responses do |response_fields| %>
      <!-- Set the value of each response field to the corresponding value from the saved response -->
      <%= response_fields.text_field :g_rating, value: response.g_rating, class: "response-#{index}-g-rating", style: "display: none;" %>
      <%= response_fields.text_field :r_rating, value: response.r_rating, class: "response-#{index}-r-rating", style: "display: none;" %>
      <%= response_fields.text_field :b_rating, value: response.b_rating, class: "response-#{index}-b-rating", style: "display: none;" %>
      <%= response_fields.text_field :a_rating, value: response.a_rating, class: "response-#{index}-a-rating", style: "display: none;" %>
      <%= response_fields.text_field :s_rating, value: response.s_rating, class: "response-#{index}-s-rating", style: "display: none;" %>
      <%= response_fields.text_field :reasoning, value: response.reasoning, class: "response-#{index}-reasoning", style: "display: none;" %>
    <% end %>
  <% end %>

<div class="progress mb-3">
  <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<%= form_for @quiz, url: { action: "update"} do |f| %>
  <div id="questions-container">
    <% @quiz.responses.each_with_index do |response, index| %>
      <%= f.fields_for :responses, index: response.id do |response_fields| %>
        <div id="question-<%= index + 1 %>" class="question-container<%= index == 0 ? '' : ' d-none' %>">
          <div class="card mb-3">
            <div class="card-body">
              <h2 class="card-title">Question <%= index + 1 %></h2>
              <p> Please listen for ~10 seconds before answering the question. Also, the "Ahhh" may play at the end of the sample.</p>
              <audio id="audio_elem_<%= index %>" controls class="mb-3">
                <source src="<%= response.sound.audio_file_path %>" type="audio/wav">
                Your browser does not support the audio element.
              </audio>

              <p>
                Hint: If you're confused about what the letters on the scale, select the anchor sample button next to the letter
                that you're listening for. This will display another audio player with a sound that is considered a level 3
                score for that voice characteristic.
              </p>
              <% ['G', 'R', 'B', 'A', 'S'].each_with_index do |letter, rating| %>
                <div class="form-group">
                  <label class="form-label"><%= letter %>:</label>
                  <div id="rating-buttons-<%= index %>-<%= letter %>" class="rating-buttons">
                    <% (0..3).each do |rating| %>
                      <button type="button" class="btn btn-secondary rating-btn" data-rating="<%= rating %>"><%= rating %></button>
                    <% end %>

                    <% if "RBAS".include?(letter) %>
                      <button id="button_anchor_<%= letter %><%= index %>" type="button" class="btn custom-lightgrey-btn" style="text-align:center; background-color: lightgrey; border-color: #4e555b; color: #4e555b"><%= letter %> Anchor Sample </button>
                      <audio id="audio_elem_anchor_<%= letter %><%= index %>" controls class="mb-3" style="display: none">
                        <source src="<%= Sound.get_anchor(letter.downcase) %>" type="audio/wav">
                        Your browser does not support the audio element.
                      </audio>
                    <% end %>

                    <%= response_fields.hidden_field "#{letter.downcase}_rating".to_sym, id: "#{index}-#{letter}-rating", class: 'rating-field' %>
                  </div>
                </div>
              <% end %>

              <div class="form-group">
                <%= response_fields.label :reasoning, "Notes:", class: 'form-label' %>
                <%= response_fields.text_field :reasoning, class: 'form-control reasoning-field' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

    <% if @quiz.num_questions > 1 %>
      <button type="button" class="btn prev-question-btn mt-3">Previous Question</button>
      <button type="button" class="btn next-question-btn mt-3">Next Question</button>
    <% end %>
  <%= f.hidden_field :complete, value: false, class: 'complete-tag' %>
  <%= f.submit "Complete Test", class: 'btn submit-quiz-button btn-grey btn-lg btn-block mt-3' %>
  <%= f.submit "Save Test", name: "save", class: 'btn btn-primary mt-3' %>
  <%= link_to 'Back', create_test_quizzes_path, class: 'btn btn-danger mt-3' %>
<% end %>
<% end %>