config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#about'
  resources :responses
  resources :quizzes do
    collection do
      get 'create_test'
      post 'create_test'
    end
    member do
        get 'results'
    end
  end
  resources :sounds do
    collection do
      get 'search'
    end
  end
  resources :groups
  resources :users do
    member do
      get 'quiz_history'
      get 'test_history'
      get 'user_statistics', to: 'statistics#user_statistics', as: 'user_statistics'
      get 'open_join_group'
      post 'join_group'
    end
  end
  match '/login', to: 'sessions#new', via: :get, :as => 'login'
  match '/login/create', to: 'sessions#create', via: :post, :as => 'sessions'
  match '/about', to: 'pages#about', via: :get, :as => 'about'
  match '/logout', to: 'sessions#destroy', via: :delete, :as => 'logout'
  match '/learn', to: 'pages#learn', via: :get, :as => 'learn'
  match '/tab_groups', to: 'pages#tab_group', via: :get, :as => 'tabGroup'
  match '/tutorial', to: 'pages#tutorial', via: :get, :as => 'tutorial'
  get 'data/audio/:filename', to: 'sounds#audio', as: 'audio', constraints: { filename: /[^\/]+/ }
  get '/quizzes/data/audio/:filename', to: 'sounds#audio', constraints: { filename: /[^\/]+/ }
  get '/sounds/data/audio/:filename', to: 'sounds#audio', constraints: { filename: /[^\/]+/ }
  get 'sounds/:sound_id/responses', to: 'responses#show_responses', as: 'responses_sound'
  get 'statistics/group/:join_token', to: 'statistics#group_statistics', as: 'group_statistics'
  get 'statistics/site', to: 'statistics#site_statistics', as: 'site_statistics'
  get 'search_users', to: 'users#search_users'
  post 'change_access', to: 'users#change_access'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Creates and saves a session token to remember user's information between sessions
  # Also makes sure emails are case insensitive in database
  before_save {|user| user.email=user.email.downcase}
  before_save :create_session_token

  # Defines the ability to be added to a group; NOT the owner, just people in the group
  has_and_belongs_to_many :groups, :join_table => "groups_users"

  # Used for tracking the "progress level" of user; see Stat model for description of
  # how progress tracking is established
  has_one :stats

  # Used to verify password fields with bcrypt
  has_secure_password

  #Validations: to confirm everything is formatted appropriately
  # Name: presence, and at a max length of 50 chars
  # Email: presence, accurate format: this@email.com are the only requirements to allow for max
  #       kinds of emails to be included,
  # Password: presence, formatting reqs: digit, lower case letter, upper case letter, and a symbol
  #        also has min reqs. for length
  # Password Confirm: does password field match password confirm (must match before user is added to database)
  # Music experience, clinical experience, and general education: Set as strings of numbers "0", "1-2","3-4", "5+" set as years; user enters these in view
  # Access Level: determines type of access: Admin, Developer, Professor, Student
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  # regex for a digit, lower case letter, upper case letter, and a symbol
  VALID_PASSWORD_REGEX = /\A(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[[:^alnum:]])/x
  validates :email, presence: true,
            format: {with: VALID_EMAIL_REGEX, message: " must be formatted correctly. The application accepts any email in an this@valid.email format."},
            uniqueness: {case_sensitive: false}
  validates :password,
            presence: true,
            format: {with: VALID_PASSWORD_REGEX, message: " must include a number (0-9), a lowercase and uppercase letter, and a symbol"},
            length: {minimum: 8}
  validates :password_confirmation, presence: true
  validates :music_experience, presence: true
  validates :clinical_experience, presence: true
  validates :general_education, presence: true
  validates :access_level, presence: true

  # Tracks and connects users to the quizzes/tests they have taken
  has_and_belongs_to_many :quizzes

  # Function: get_individual_quiz_grades obtains all the quizzes grades individual to letter for individual user
  # finds all quizzes the user has taken, checks whether the quiz has been completed
  # If the quiz has been completed it's added to a hash-map containing all GRBAS letters
  # to obtain overall number of questions and right answers for each letter
  # of the GRBAS scale
  # Return type: Hashmap [ "letter from GRBAS" => [num_right, total_num_questions]]
  def get_individual_quiz_grades
    # Get all quizzes for each letter
    quizzes = []
    letters = ['g', 'r', 'b', 'a', 's']
    letters.each do |letter|
      quiz_letter = self.quizzes.where('which_grbas_letter = ? AND completed IS true', letter)
      quizzes << quiz_letter
    end

    # Sum over these quizzes
    grades = []
    quizzes.each do |quiz_letter|
      letter_grades = [0,0]
      quiz_letter.each do |quiz| # saves the quiz data in format [num_right, num_questions]
        letter_grades[0] += quiz.num_right
        letter_grades[1] += quiz.num_questions
      end
      grades << letter_grades
    end

    # Zip map the letters to the grades
    Hash[letters.zip(grades)]
  end

  # Function: get_test_grades obtains all tests grades for individual user
  # Finds all the tests taken by individual user (marked by a lack of "GRBAS" letter in the "which_grbas_letter" property)
  # then finds which ones have been completed, and determines the total number of questions
  # and which ones were answered correctly
  # Return type: Array [num_right, total_num_questions]
  def get_test_grades
    tests = self.quizzes.where('which_grbas_letter = ? AND completed IS true', '')
    grades = [0,0]
    tests.each do |test|
      grades[0] += test.num_right unless test.num_right.nil?
      grades[1] += test.num_questions unless test.num_questions.nil?
    end
    grades
  end

  # Function: get_site_quiz_grades obtains all the quizzes grades individual to letter for entire database
  # finds all quizzes taken, checks whether the quiz has been completed
  # If the quiz has been completed it's added to a hash-map containing all GRBAS letters
  # to obtain overall number of questions and right answers for each letter
  # of the GRBAS scale
  # Return type: Hashmap [ "letter from GRBAS" => [num_right, total_num_questions]]
  def self.get_site_quiz_grades
    users = User.all
    total_quiz_hash = {}
    for user in users  # get all users in group
      # Keys: GRBAS, Values: [num_correct, total_questions]
      quiz_hash = user.get_individual_quiz_grades # see user documentation for this method
      quiz_hash.each do |key, value|
        if total_quiz_hash[key] # if key already has some value stored, add the next value
          total_quiz_hash[key] += value
        else # otherwise store the value for that key
          total_quiz_hash[key] = value
        end
      end
    end
    total_quiz_hash
  end

  # Function: get_test_grades obtains all tests grades for entire database
  # Finds all the tests (marked by a lack of "GRBAS" letter in the "which_grbas_letter" property)
  # then finds which ones have been completed, and determines the total number of questions
  # and which ones were answered correctly
  # Return type: Array [num_right, total_num_questions]
  def self.get_site_test_grades
    users = User.all
    total_test_scores = [0,0]
    for user in users # get all users in group
      test = user.get_test_grades # see earlier documentation
      unless test[0].nil? || test[1].nil?
        total_test_scores[0] += test[0]
        total_test_scores[1] += test[1]
      end
    end
    total_test_scores
  end

  # Private function: Used to create the initial session token for when users are created and saved
  # to database. Uses SecureRandom.urlsafe_base64 as a basis for creating session tokens
  # individual to users.
  private
  def create_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
/
Allows users to access their own information. Also allows for admins & devs to search for users and
change their access levels.
/
class UsersController < ApplicationController
  before_action :set_current_user, except: [:new, :create]
  before_action :verify_admin_or_dev, only: [:search_users, :change_access]

  def show
    id = params[:id]
    if !current_user?(id)
      flash[:warning]="Can only show profile of logged-in user"
      redirect_to user_path(@current_user.id)
    end
  end

  def search_users
    if params[:search].nil? || params[:search].empty?
      @users = []
    else
      @users = User.where("name LIKE ? OR email LIKE ?",
                          "%#{params[:search]}%".downcase, "%#{params[:search]}%".downcase)
    end
  end

  def change_access
  @user = User.find(params[:id])
  if @user == @current_user || (@user.access_level == "Admin" && @current_user.access_level != "Developer")
    flash[:alert] = "You cannot change the access level of yourself or admins."
    redirect_to search_users_path
    return
  end
  if params[:access] == "Admin" || params[:access] == "Student" || params[:access] == "Professor"
    @user.update_attribute(:access_level, params[:access])
  end
  if @user[:access_level] == params[:access]
    flash[:notice] = "Access level changed."
  else
    flash[:alert] = "Failed to change access level. This is case sensitive and must match 'Admin', 'Student', or 'Professor'"
  end
  render 'search_users'
end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @user.update({:new_user => true})
    if @user.save
      flash[:notice] = "Sign up successful! Welcome to THE!"
      @stat = Stat.create({:user_id => @user.id})
      @stat.save
      @stat.set_progress_level
      redirect_to groups_path
    else
      errors = @user.errors.full_messages
      flash[:notice] = "Validation failed with errors: #{errors.join(', ')}"
      render 'new'
    end
  end

  def edit
    # render 'edit'
  end

  def update
    # update product
  end

  def destroy
    # destroy user
  end

  def quiz_history
    @quiz_history = @current_user.quizzes.where.not(which_grbas_letter: "").order(created_at: :desc)
  end

  def test_history
    @test_history = @current_user.quizzes.where(which_grbas_letter: "").order(created_at: :desc)
  end

  def open_join_group
    render 'join_group'
  end

  def join_group
    join_token = user_params[:join_token]
    @group = Group.find_group(join_token)
    if !@current_user.groups.include?(@group) && !@group.eql?(false)
      @current_user.groups << @group
      flash[:notice] ="You have just joined " + @group.name + "."
      redirect_to groups_path
    elsif @group.eql?(false)
      flash[:notice] = "Please try again, group code was either incorrect or group does not exist"
      render 'join_group'
    else
      flash[:notice] = "You've already joined this group. Please check the existing groups tab."
      render 'join_group'
    end
  end

  private
    def user_params
      params.require(:user).permit(:id, :name, :email, :address,:password,:password_confirmation,
                                   :music_experience, :clinical_experience, :general_education,
                                   :access_level, :join_token)
    end

    def verify_admin_or_dev
      redirect_to root_path, alert: 'Access denied.' unless @current_user.access_level.eql?("Admin") ||
        @current_user.access_level.eql?("Developer")
    end
end

app/views/users/join_group.html.erb
<%= form_tag join_group_user_path(@current_user.id), method: :post, class: 'needs-validation', novalidate: true do %>
  <%= fields_for :user do |form| %>

    <div class="form-group">
      <p> Please enter the code associated to the group you're assigned by a professor.
      Understand that by entering the code and joining the group, you're giving permission to the group owner
      to have access to your statistics regarding quizzes, feedback, notes, etc. </p>
    </div>

    <div class="form-group">
      <%= form.label :join_token, "Group Code:", class: 'form-label' %>
      <%= form.text_field :join_token, class: 'form-control' %>
    </div>

    <div class="text-center">
      <%= submit_tag "Join", class: 'btn btn' %>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1 class="mb-4">Create A New User</h1>

<%= form_tag users_path, method: :post, class: 'needs-validation', novalidate: true do %>
  <%= fields_for :user do |form| %>
    <div class="form-group">
      <%= form.label :access_level, "Professor or Student?", class: 'form-label' %>
      <%= form.select :access_level, ['Professor', 'Student'], {}, { class: 'form-control custom-input' } %>
    </div>

    <div class="form-group">
      <%= form.label :name, "Username:", class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :email, "Email:", class: 'form-label' %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <p class="form-label"><strong>*Password must include 8 min chars, a number, a symbol, at least 1 uppercase letter, and 1 lowercase letter</strong></p>

    <div class="form-group">
      <%= form.label :password, "Password:", class: 'form-label' %>
      <%= form.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation, "Confirm Password:", class: 'form-label' %>
      <%= form.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :music_experience, "Years of Music Experience", class: 'form-label' %>
      <%= form.select :music_experience, ['0','1-2','3-4', '5+'], {}, { class: 'form-control custom-input' } %>
    </div>

    <div class="form-group">
      <%= form.label :clinical_experience, "Years of Clinical Experience", class: 'form-label' %>
      <%= form.select :clinical_experience, ['0','1-2','3-4', '5+'], {}, { class: 'form-control custom-input' } %>
    </div>

    <div class="form-group">
      <%= form.label :general_education, "Years of General Education (related to speech language pathology only)", class: 'form-label' %>
      <%= form.select :general_education, ['0','1-2','3-4', '5+'], {}, { class: 'form-control custom-input' } %>
    </div>

    <div class="text-center">
      <%= submit_tag "Create User", class: 'btn btn' %>
    </div>
  <% end %>
<% end %>

<style>
    .form-label {
        font-weight: bold;
    }
    .form-control {
        margin-bottom: 10px;
    }
    .text-center {
        margin-top: 20px;
    }
</style>

app/views/users/quiz_history.html.erb
<h1>Your Quiz History</h1>

<% if @quiz_history.empty? %>
  <p>You have not taken any quizzes yet.</p>
<% else %>
  <% @quiz_history.group_by { |quiz| quiz.which_grbas_letter }.each do |grbas_letter, quizzes| %>
    <details>
      <summary><%= grbas_letter.upcase %></summary>
      <% quizzes.each do |quiz| %>
        <% grade_percent = quiz.num_questions.zero? ? 0 : (quiz.num_right.to_f / quiz.num_questions) * 100 %>
        <% completion_class = quiz.completed ? 'quiz-completed' : 'quiz-incomplete' %>
        <style>
            .<%= completion_class %> {
                background-color: <%= quiz.completed ? 'lightgreen' : 'lightcoral' %>;
                border-radius: 10px;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #ddd;
                margin-left: 20px;
            }
        </style>
        <div class="<%= completion_class %>">
          <p>Quiz --> Difficulty: <%= quiz.difficulty %> |
            Number of Questions: <%= quiz.num_questions %> |
            Created: <%= quiz.created_at.in_time_zone("Central Time (US & Canada)").strftime("%I:%M%p") %> |
            <% if !quiz.completed %>
              (Incomplete)
              <%= link_to 'Resume', quiz_path(quiz), class: 'btn btn-primary', style: 'margin-left: 20px;' %>
            <% else %>
              Grade: <%= quiz.num_right.to_s %> / <%= quiz.num_questions.to_s %>
            <% end %>
          </p>
          <% if quiz.completed %>
            <% quiz.responses.each do |response| %>
              <div class="response-box">
                <p><strong>Sound:</strong> <%= Sound.find_by_id(response.sound_id).db_file_name %></p>
                <p><strong>Rating:</strong> <%= response["#{quiz.which_grbas_letter}_rating".to_sym] %></p>
                <p><strong>Your Reasoning:</strong> <%= response.reasoning %></p>
                <p><strong>Expert Feedback:</strong> <%= simple_format(response.feedback) %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </details>
  <% end %>
<% end %>

<style>
    .response-box {
        background-color: #f8f9fa;
        border-radius: 10px;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ddd;
        margin-left: 20px;
    }

    details > summary {
        font-size: 1.5em;
        border: 1px solid #aaa;
        padding: 10px;
        margin-bottom: 10px;
        background-color: transparent;
        border-radius: 10px;
    }
</style>

app/views/users/search_users.html.erb
<div class="container">
  <h1>Search Users</h1>
  <%= form_with(url: search_users_path, method: :get, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :search, 'Search for a user:' %>
      <%= form.text_field :search, class: 'form-control' %>
    </div>
    <%= form.submit 'Search', class: 'btn btn-primary' %>
  <% end %>

  <% if @users.present? %>
    <div class="mt-4">
      <h2>Search Results</h2>
      <ul class="list-group">
        <% @users.each do |user| %>
          <li class="list-group-item">
            <h3><%= user.name %></h3>
            <p>Email: <%= user.email %></p>
            <%= form_with(url: change_access_path, method: :post, local: true) do |form| %>
              <div class="form-group">
                <%= form.label :access, 'Access Level:' %>
                <%= form.text_field :access, class: 'form-control', value: user.access_level %>
                <%= form.hidden_field :id, value: user.id %>
              </div>
              <%= form.submit 'Change Access', class: 'btn btn-primary' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp - Profile</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <style>
      .profile-header {
          background-color: #f8f9fa;
          padding: 20px;
          border-radius: 5px;
          margin-bottom: 20px;
      }
      .profile-info {
          margin-bottom: 10px;
      }
      .custom-lightgrey-btn {
          background-color: lightgrey;
          color: black;
          border: none;
      }
      .custom-lightgrey-btn:hover {
          background-color: grey;
          color: white;
      }
  </style>
</head>
<body>



<div class="container">
  <div class="profile-header">
    <h1>Profile for: <%= @current_user.name %></h1>

    <div>
      <p>
        The user profile allows you to access all personal history regarding quizzes and tests. For accessing quiz history select “Quiz History".
        This will describe all your previous results, their associated sounds, and all the notes you left for that quiz.
        “Test History” will do the same thing, but for all your testing practice history. If you are unsure what Quiz vs Test means,
        please check out the “Learn” tab (on the top bar) which will tell you more about what these are for during your practice).
      </p>
    </div>

    <p class="profile-info"><strong>Name:</strong> <%= @current_user.name %></p>
    <p class="profile-info"><strong>Email:</strong> <%= @current_user.email %></p>
    <p class="profile-info"><strong>Music Experience:</strong> <%= @current_user.music_experience %> years</p>
    <p class="profile-info"><strong>Clinical Experience:</strong> <%= @current_user.clinical_experience %> years</p>
    <p class="profile-info"><strong>General Education:</strong> <%= @current_user.general_education %> years</p>

    <%= link_to "Quiz History", quiz_history_user_path(@current_user.id), class: 'btn custom-lightgrey-btn' %>
    <%= link_to "Test History", test_history_user_path(@current_user.id), class: 'btn custom-lightgrey-btn' %>
    <%= link_to "User Statistics", user_statistics_user_path(@current_user.id), class: 'btn custom-lightgrey-btn' %>
    <% if @current_user.access_level.eql?("Admin") %>
      <%= link_to "Site Statistics", site_statistics_path(@current_user.id), class: 'btn custom-lightgrey-btn' %>
    <% end %>
    <% if @current_user.access_level.eql?("Admin") || @current_user.access_level.eql?("Developer")%>
      <%= link_to 'Search Users', search_users_path(@current_user), class: 'btn custom-lightgrey-btn' %>
    <% end %>
  </div>
</div>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/users/test_history.html.erb
<h1>Your Test History</h1>

<% if @test_history.empty? %>
  <p>You have not taken any tests yet.</p>
<% else %>
  <% @test_history.group_by { |test| test.created_at.to_date }.each do |date, tests| %>
    <details>
      <summary><%= date.strftime("%B %d, %Y") %></summary>
      <% tests.each do |test| %>
        <% completion_class = test.completed ? 'quiz-completed' : 'quiz-incomplete' %>
        <style>
            .<%= completion_class %> {
                background-color: <%= test.completed ? 'lightgreen' : 'lightcoral' %>;
                border-radius: 10px;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #ddd;
                margin-left: 20px;
            }
        </style>

        <div class="<%= completion_class %>">
          <p>Difficulty: <%= test.difficulty %></p>
          <p>Number of Questions: <%= test.num_questions %></p>
          <p>Taken On: <%= test.created_at.in_time_zone("Central Time (US & Canada)").strftime("%I:%M%p") %></p>
          <% if !test.completed %>
            (Incomplete)
            <%= link_to 'Resume', quiz_path(test), class: 'btn btn-primary', style: 'margin-left: 20px;' %>
          <% else %>
            <% test.responses.each do |response| %>
              <div class="response-box">
                <p><strong>Sound:</strong> <%= Sound.find_by_id(response.sound_id).db_file_name %></p>
                <% ["g", "r", "b", "a", "s"].each do |letter| %>
                  <p><strong><%= letter.upcase %> Rating:</strong> <%= response["#{letter}_rating".to_sym] %></p>
                <% end %>
                <p><strong>Your Reasoning:</strong> <%= response.reasoning %></p>
                <p><strong>Expert Feedback:</strong> <%= simple_format(response.feedback) %></p>
              </div>
            <% end %>
          <% end %>

        </div>
      <% end %>
    </details>
  <% end %>
<% end %>

<style>
    .response-box {
        background-color: #f8f9fa;
        border-radius: 10px;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ddd;
        margin-left: 20px;
    }

    details > summary {
        font-size: 1.5em;
        border: 1px solid #aaa;
        padding: 10px;
        margin-bottom: 10px;
        background-color: transparent;
        border-radius: 10px;
    }
</style>