config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#about'
  resources :responses
  resources :quizzes do
    collection do
      get 'create_test'
      post 'create_test'
    end
    member do
        get 'results'
    end
  end
  resources :sounds do
    collection do
      get 'search'
    end
  end
  resources :groups
  resources :users do
    member do
      get 'quiz_history'
      get 'test_history'
      get 'user_statistics', to: 'statistics#user_statistics', as: 'user_statistics'
      get 'open_join_group'
      post 'join_group'
    end
  end
  match '/login', to: 'sessions#new', via: :get, :as => 'login'
  match '/login/create', to: 'sessions#create', via: :post, :as => 'sessions'
  match '/about', to: 'pages#about', via: :get, :as => 'about'
  match '/logout', to: 'sessions#destroy', via: :delete, :as => 'logout'
  match '/learn', to: 'pages#learn', via: :get, :as => 'learn'
  match '/tab_groups', to: 'pages#tab_group', via: :get, :as => 'tabGroup'
  match '/tutorial', to: 'pages#tutorial', via: :get, :as => 'tutorial'
  get 'data/audio/:filename', to: 'sounds#audio', as: 'audio', constraints: { filename: /[^\/]+/ }
  get '/quizzes/data/audio/:filename', to: 'sounds#audio', constraints: { filename: /[^\/]+/ }
  get '/sounds/data/audio/:filename', to: 'sounds#audio', constraints: { filename: /[^\/]+/ }
  get 'sounds/:sound_id/responses', to: 'responses#show_responses', as: 'responses_sound'
  get 'statistics/group/:join_token', to: 'statistics#group_statistics', as: 'group_statistics'
  get 'statistics/site', to: 'statistics#site_statistics', as: 'site_statistics'
  get 'search_users', to: 'users#search_users'
  post 'change_access', to: 'users#change_access'
end

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= stylesheet_link_tag 'about', media: 'all', 'data-turbolinks-track': true %>
  <title>The GRBAS Scale</title>
</head>
<body>
<div class="container">
<div class="box">
  <h2>Welcome!</h2>
  <pre>
    <strong>Where to start?</strong>
    Hello! So glad to hear you’ve decided to test your GRBAS skills! There are some fun
    options for learning in our application, to do so, please select the Learn
    tab on the top bar! Once you’ve started practicing and you’d like to check review your previous
    practice, check out the user tab to find your quiz/test histories and some personal stats!

    <strong>What are groups?</strong>
    If you’re a Professor account and would like to keep track of how your students are performing,
    you can make a group to check in on all the students apart of the groups you’ve created.
    Once you’ve created the group, simply have your students join the group through their own
    accounts using the join code provided (you’ll find this by locating your current groups page)!

    For Students, groups are mostly for tracking a group’s progress for a Professor.
    To join a group your Professor assigns to you, find the join groups tab (underneath the
    Groups tab along the top bar) and select join group. Enter in the join code
    given to you by your Professor.

    </pre>
</div>
<div> <p></p></div>
  <h2>The GRBAS Scale</h2>
  <ul>
    <li><strong>G</strong> - Grade of Hoarseness - relating to overall level of disorder</li>
    <li><strong>R</strong> - Roughness - irregularity in vocal vibrations, specific listening</li>
    <li><strong>B</strong> - Breathiness - air leakage thru vocal folds, tend to sound like white noise</li>
    <li><strong>A</strong> - Asthenia - weakness or lack of power</li>
    <li><strong>S</strong> - Strain - throat constriction / tone can have high pitch features</li>
  </ul>
  <div> <p></p></div>
  <h3>About</h3>
  <div class="box">
    <pre>
    GRBAS is a perceptual scale that can be used to distinguish some voice
    characteristics. It is mainly used to train the ear to distinguish the
    severity of certain characteristics within the voice ie how much
    strain or weakness is present in the voice. The numerical scale is
    set from 0 to 3. A 0 should represent a normal voice (lack of disorder),
    a 1 is mildly disordered, 2 is moderately disordered, and a 3 is severely disordered.
    This scale is not a complete evaluation or assessment of a patient's condition
    and is only intended for a more objective approach to listening for certain voices.
    </pre>
  </div>
  <h3>Sources and Credits</h3>
  <p>
    Walden, Patrick R (2020), “Perceptual Voice Qualities Database (PVQD)”, Mendeley Data, v2,
    <a href="https://data.mendeley.com/datasets/9dz247gnyb/1">https://data.mendeley.com/datasets/9dz247gnyb/1</a>
  </p>
</div>
</body>
</html>

app/views/pages/learn.html.erb
<!DOCTYPE html>
<html lang="">
<head>
  <title>RailsApp - Learn</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <style>
      .profile-header {
          background-color: #f8f9fa;
          padding: 20px;
          border-radius: 5px;
          margin-bottom: 20px;
      }
      .profile-info {
          margin-bottom: 10px;
      }
      .custom-lightgrey-btn {
          background-color: lightgrey;
          color: black;
          border: none;
      }
      .custom-lightgrey-btn:hover {
          background-color: grey;
          color: white;
      }
  </style>
</head>
<body>

<div class="container">
  <div class="profile-header">
    <h1>Learn GRBAS </h1>
    <div class="box">
      <p><strong>Practice can be done in a few ways. Here’s what each learn method does:</strong></p>
      <ul>
        <li><strong>Listen to Sounds</strong> - get acquainted to the sounds that are available on the application by having all the current sounds listed with their current GRBAS scores.</li>
        <li><strong>Quizzes</strong> - practicing 1 letter of the GRBAS scale.</li>
        <li><strong>Tests</strong> - practicing all 5 letters in the GRBAS scale.</li>
      </ul>
      <p></p>
    </div>
    <%= link_to "Listen to Sounds", sounds_path, class: 'btn custom-lightgrey-btn' %>
    <%= link_to "Create New Quiz", new_quiz_path(@current_user.id), class: 'btn custom-lightgrey-btn' %>
    <%= link_to "Create New Test", create_test_quizzes_path(@current_user.id), class: 'btn custom-lightgrey-btn' %>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/tabGroup.html.erb
<!DOCTYPE html>
<html lang="">
<head>
  <title>RailsApp - Learn</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <style>
      .profile-header {
          background-color: #f8f9fa;
          padding: 20px;
          border-radius: 5px;
          margin-bottom: 20px;
      }
      .profile-info {
          margin-bottom: 10px;
      }
      .custom-lightgrey-btn {
          background-color: lightgrey;
          color: black;
          border: none;
      }
      .custom-lightgrey-btn:hover {
          background-color: grey;
          color: white;
      }
  </style>
</head>
<body>

<div class="container">
  <div class="profile-header">
    <h1>Groups: </h1>
    <% if @current_user.access_level.eql?("Professor") %>
      <%= link_to "Add a Group", new_group_path, class: 'btn custom-lightgrey-btn' %>
      <%= link_to "Groups Owned", groups_path, class: 'btn custom-lightgrey-btn' %>
      <% end %>
    <% if @current_user.access_level.eql?("Student") %>
      <%= link_to 'Join A Group', open_join_group_user_path(@current_user.id) %>
      <%= link_to 'Joined Groups', groups_path %>
    <% end %>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/tab_group.html.erb
<!DOCTYPE html>
<html lang="">
<head>
  <title>RailsApp - Learn</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <style>
      .profile-header {
          background-color: #f8f9fa;
          padding: 20px;
          border-radius: 5px;
          margin-bottom: 20px;
      }
      .profile-info {
          margin-bottom: 10px;
      }
      .custom-lightgrey-btn {
          background-color: lightgrey;
          color: black;
          border: none;
      }
      .custom-lightgrey-btn:hover {
          background-color: grey;
          color: white;
      }
  </style>
</head>
<body>

<div class="container">
  <div class="profile-header">
    <h1>Groups: </h1>
    <% if @current_user.access_level.eql?("Professor") %>
      <div>
        <p>
          Would you like to keep track of how your students are performing? You can make a group to check in on all
          the students by selecting “Create Group”. Once you’ve created the group, simply have your
          students join the group through their own accounts using the join code provided
          (you’ll find this by locating your current groups page)!
        </p>
        <p>
          You can see each group you’ve created under “Owned Groups”.
          For each group you’ll also see where you can access
          “Group Stats” which will provide basic statistical information
          conveying how the group is currently performing during practice.
          It will also display all the current students apart of that specific group.
        </p>
      </div>

      <%= link_to "Add a Group", new_group_path, class: 'btn custom-lightgrey-btn' %>
      <%= link_to "Groups Owned", groups_path, class: 'btn custom-lightgrey-btn' %>
    <% end %>
    <% if @current_user.access_level.eql?("Student") %>
      <div>
        <p>
          Groups are mostly for Professors to check in on how their students are doing.
          For you, you’ll need to join a group based by selecting “Join Group” and inputting the join code
          that the Professor has provided to you. To see which groups you are currently apart of,
          you can select “Joined Groups”.
        </p>
      </div>
      <%= link_to 'Join A Group', open_join_group_user_path(@current_user.id), class: 'btn custom-lightgrey-btn' %>
      <%= link_to 'Joined Groups', groups_path, class: 'btn custom-lightgrey-btn' %>
    <% end %>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/tutorial.html.erb
<div class="container">
<div class="profile-header">
  <h2>Welcome!</h2>
  <p>Hello! So glad to hear you’ve decided to test your GRBAS skills! We are excited to see you get started with learning about GRBAS!</p>

  <p>First and foremost, welcome! Now, what is Teaching Hearing Easy? </p>

  <p>Teaching Hearing Easy lets users start refining their hearing skills
    using a perceptual scale called GRBAS. Users will listen to a sound
    and scale the sound to determine if there's any disorder in the voice.
    This will be scaled on a 0-3 scale for each letter in the GRBAS acronym (0 being a normal voice, 3 being severely disordered).
  </p>

  <h2>The GRBAS Scale</h2>
  <ul>
    <li><strong>G</strong> - Grade of Hoarseness - relating to overall level of disorder</li>
    <li><strong>R</strong> - Roughness - irregularity in vocal vibrations, specific listening</li>
    <li><strong>B</strong> - Breathiness - air leakage thru vocal folds, tend to sound like white noise</li>
    <li><strong>A</strong> - Asthenia - weakness or lack of power</li>
    <li><strong>S</strong> - Strain - throat constriction / tone can have high pitch features</li>
  </ul>

  <p>Thus, if you hear what you believe is a normal voice, you'd scale the sound
    at a G0. Teaching Hearing Easy uses different approaches of practice
    geared towards users improving their own internal perceptual scale.
  </p>


  <p> Now that you know, we'd like you to start by taking a quick diagnostic test!
  This will help us determine where you might be in terms of expertise!</p>


  <p> Please click the below button to get started!</p>

  <%= link_to "New Test", create_test_quizzes_path(@current_user.id), class: 'btn custom-lightgrey-btn' %><br>

  <p>(If you don't want to take the diagnostic test, your account will be set
    according to the experience levels you entered during the user creation
    process.)
    </p>
</div>
</div>

<style>
    .profile-header {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 5px;
        margin-bottom: 20px;
    }
    .profile-info {
        margin-bottom: 10px;
    }
    .custom-lightgrey-btn {
        background-color: lightgrey;
        color: black;
        border: none;
    }
    .custom-lightgrey-btn:hover {
        background-color: grey;
        color: white;
    }
</style>