config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#about'
  resources :responses
  resources :quizzes do
    collection do
      get 'create_test'
      post 'create_test'
    end
    member do
        get 'results'
    end
  end
  resources :sounds do
    collection do
      get 'search'
    end
  end
  resources :groups
  resources :users do
    member do
      get 'quiz_history'
      get 'test_history'
      get 'user_statistics', to: 'statistics#user_statistics', as: 'user_statistics'
      get 'open_join_group'
      post 'join_group'
    end
  end
  match '/login', to: 'sessions#new', via: :get, :as => 'login'
  match '/login/create', to: 'sessions#create', via: :post, :as => 'sessions'
  match '/about', to: 'pages#about', via: :get, :as => 'about'
  match '/logout', to: 'sessions#destroy', via: :delete, :as => 'logout'
  match '/learn', to: 'pages#learn', via: :get, :as => 'learn'
  match '/tab_groups', to: 'pages#tab_group', via: :get, :as => 'tabGroup'
  match '/tutorial', to: 'pages#tutorial', via: :get, :as => 'tutorial'
  get 'data/audio/:filename', to: 'sounds#audio', as: 'audio', constraints: { filename: /[^\/]+/ }
  get '/quizzes/data/audio/:filename', to: 'sounds#audio', constraints: { filename: /[^\/]+/ }
  get '/sounds/data/audio/:filename', to: 'sounds#audio', constraints: { filename: /[^\/]+/ }
  get 'sounds/:sound_id/responses', to: 'responses#show_responses', as: 'responses_sound'
  get 'statistics/group/:join_token', to: 'statistics#group_statistics', as: 'group_statistics'
  get 'statistics/site', to: 'statistics#site_statistics', as: 'site_statistics'
  get 'search_users', to: 'users#search_users'
  post 'change_access', to: 'users#change_access'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="">
<head>
  <title>THE</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= javascript_importmap_tags %>
</head>
<body>

<% if flash[:notice].present? %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <a class="navbar-brand" href="<%= about_path %>">Teaching Hearing Easy</a>
  <div class="navbar-nav">
    <% if @current_user.nil? %>
      <%= link_to 'Login', login_path, class: 'nav-item nav-link btn btn-outline-warning' %>
      <%= link_to 'New User', new_user_path, class: 'nav-item nav-link btn btn-outline-warning' %>
  <% else %>
      <%= link_to 'Learn', learn_path, class: 'nav-item nav-link btn btn-outline-warning' %>
      <%= link_to 'Profile', user_path(@current_user.id), class: 'nav-item nav-link btn btn-outline-warning' %>
      <%= link_to 'Groups', tabGroup_path, class: 'nav-item nav-link btn btn-outline-warning' %>
      <%= button_to 'Log Out', logout_path, method: :delete, class: 'nav-item nav-link btn-outline-danger' %>
    <% end %>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>